from src.features import (
    binding,
    evaluation,
    implementation,
    parameterPassing,
    parsing,
    scoping,
    typing
)

from sys import argv
from json import load
from os.path import abspath



def build() -> None:

    PATH = abspath(f"{__file__}/../..")

    with open(f"{PATH}/core/config.json", "r") as data: 
        config = load(data)
    
    with open(f"{PATH}/core/methods.py") as methods: 
        methods = methods.readlines()


    features = {
        "typing"            : (typing.Dynamic, typing.Static),
        "binding"           : (binding.NormalOrder, binding.ApplicativeOrder),
        "parsing"           : (parsing.Parser,),
        "scoping"           : (scoping.Dynamic, scoping.Static),
        "evaluation"        : (evaluation.Evaluate,),
        "implementation"    : (implementation.Interpreter, implementation.Compiler),
        "parameterPassing"  : (parameterPassing.PassByValue, parameterPassing.PassByReference)
        }


    BASES: tuple[type] = tuple(f"{feature}.{choices[config["features"][feature]].__name__}" for feature, choices in features.items())
    FEATURES: dict = config["features"]


    with open(f"{PATH}/core/opal.py", "w") as file: 
        embed = lambda x, sep="\n    ": sep.join(x).strip()

        file.write(f"""# !! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!
            
from src.keywords import *

from src.features import (
    {embed(FEATURES.keys(), ",\n    ")}
)
            
from rich import print



class OPAL(
    {embed(BASES, ",\n    ")}
    ):

    # flags
    {embed(f"{var[1]}Flag = {var in argv}" for var in config["flags"])}

    # details
    {embed(f"{var.upper().replace(" ", "_")} = '{val}'" for var, val in config["details"].items())}

    # options
    {embed(f"{var.upper().replace(" ", "_")} = '{val}'" for var, val in config["options"].items())}

    # features
    FEATURES = {{
        {embed([
            f"'{var}' {" " * (len(max(config["features"].keys(), key=len)) - len(var))} : {(val, features[var][val].__name__)}" 
            for var, val in config["features"].items()
            ], ",\n        ")}
        }}

    PATH = '{PATH}'

    REGULAR = REGULAR
    IRREGULAR = IRREGULAR
    BOOLEAN = BOOLEAN
    SPECIAL = SPECIAL

    
    {embed(methods, "    ")}



opal = OPAL()
""")
