from src.features import (
    binding,
    evaluation,
    implementation,
    parameterPassing,
    parsing,
    scoping,
    typing
)


from json import load

from os.path import abspath

from importlib import reload



def build() -> None:
    PATH = abspath(f"{__file__}/../..")

    with open(f"{PATH}/core/config.json", "r") as data: 
        config = load(data)
    
    with open(f"{PATH}/core/methods.py") as methods: 
        methods = "    ".join(methods.readlines())


    features = {
        "binding"           : (binding.NormalOrder, binding.ApplicativeOrder),
        "evaluation"        : (evaluation.Evaluate,),
        "implementation"    : (implementation.Interpreter, implementation.Compiler),
        "parameterPassing"  : (parameterPassing.PassByValue, parameterPassing.PassByReference),
        "parsing"           : (parsing.Parser,),
        "scoping"           : (scoping.Dynamic, scoping.Static),
        "typing"            : (typing.Dynamic, typing.Static)
        }


    BASES: tuple[type] = tuple(f"{feature}.{choices[config["language"][feature]].__name__}" for feature, choices in features.items())


    with open(f"{PATH}/core/opal.py", "w") as file: 
        file.write(f"""# !! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!
            
from src.keywords import *

from src.features import (
    binding,
    evaluation,
    implementation,
    parameterPassing,
    parsing,
    scoping,
    typing
)
            
from rich import print

            
                            
class OPAL(
    {",\n    ".join(BASES)}
    ):

    {"\n    ".join(f"{var.upper().replace(" ", "_")} = '{val}'" for var, val in config["options"].items())}

    PATH = '{PATH}'

    REGULAR = REGULAR
    IRREGULAR = IRREGULAR
    BOOLEAN = BOOLEAN
    SPECIAL = SPECIAL

    
    {methods}



opal = OPAL()
""")
