# !! THIS FILE IS AUTOMATICALLY GENERATED - PLEASE DO NOT MODIFY !!
            
from src.keywords import *

from src.features import (
    typing,
    binding,
    parsing,
    scoping,
    evaluation,
    implementation,
    parameterPassing
)
            
from rich import print



class OPAL(
    typing.Dynamic,
    binding.NormalOrder,
    parsing.Parser,
    scoping.Dynamic,
    evaluation.Evaluate,
    implementation.Interpreter,
    parameterPassing.PassByValue
    ):

    # flags
    iFlag = True
    dFlag = False

    # details
    NAME = 'OPAL'
    VERSION = '0.0.1'

    # options
    PROMPT = '(Ω) '
    SINGLE_COMMENT = '--'
    MULTILINE_COMMENT_OPEN = '*/'
    MULTILINE_COMMENT_CLOSE = '/*'
    DEFAULT_COLOR = 'green'

    # features
    FEATURES = {
        'typing'            : (0, 'Dynamic'),
        'binding'           : (0, 'NormalOrder'),
        'parsing'           : (0, 'Parser'),
        'scoping'           : (0, 'Dynamic'),
        'evaluation'        : (0, 'Evaluate'),
        'implementation'    : (0, 'Interpreter'),
        'parameterPassing'  : (0, 'PassByValue')
        }

    PATH = '/home/ai/github/OPAL/src'

    REGULAR = REGULAR
    IRREGULAR = IRREGULAR
    BOOLEAN = BOOLEAN
    SPECIAL = SPECIAL

    
    def info(self) -> None:
        offset = int(len(max(self.FEATURES.keys(), key=len)) * 1.25)
    
        print(f"OPAL is a Parameterized Adaptive Language")
        for feature, (idx, selection) in self.FEATURES.items():
            print(f"{feature[0].upper()}{feature[1:]} {"."*(offset-len(feature))} | {idx} | {selection}")
        print(f"Version {self.VERSION}")
    
    
    def get_methods(self) -> list:
        return [method for method in self.__dir__() if not method.startswith("__")]
    
    
    def call(self, event: str, *args, **kwargs) -> any:
        return self.__getattribute__(f"event_{event.lower().replace(" ", "_")}")(*args, **kwargs)
    
    
    def __repr__(self) -> str:
        return f"OPAL {self.VERSION}"



opal = OPAL()
